services:
  # Database untuk n8n (Opsional, tapi disarankan agar workflow tidak hilang)
  postgres_n8n:
    image: postgres:15
    environment:
      - POSTGRES_DB=n8n_db
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_pass
    volumes:
      - pg_n8n_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5679:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_HOST=postgres_n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_pass
      - N8N_TUNNEL=true
      - WEBHOOK_URL=https://idaho-televisions-encountered-starsmerchant.trycloudflare.com
  
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres_n8n
  
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: bigdata-cloudflare-tunnel
    restart: always
    command: tunnel --url http://n8n:5678

  # MongoDB untuk menampung hasil extraksi berita (NoSQL cocok untuk data teks berita)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Metabase untuk Dashboard
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - bigdata_metabase_data:/metabase.db
    restart: always

volumes:
  pg_n8n_data:
  n8n_data:
  mongo_data:
  metabase_data:
  bigdata_metabase_data:
    external: true

